version: '3.8'

services:
  # 1. Database PostgreSQL dengan Volume Permanen (Tugas Backend)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123password
      POSTGRES_DB: kemiskinan_db
    ports:
      - "5432:5432"
    volumes:
      - db_poverty_data:/var/lib/postgresql/data

  # 2. Backend Flask (Tugas Backend)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend 
    ports:
      - "8080:5000" # Di-mapping ke port 8080 sesuai modul
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin123password
      - DB_NAME=kemiskinan_db

  # 3. Frontend Streamlit (Tugas Frontend)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend 
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  db_poverty_data: # 🌟 Named Volume agar data DB tidak hilang saat restart
