FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose port internal Flask
EXPOSE 5000

# Menjalankan file backend Flask kita
CMD ["python", "backend_app.py"]
